version: '3.9'

services:
  fastapi-app:
    image: dhiraj918106/fastapi_jenkins:latest  # Updated to your Docker Hub repo
    container_name: fastapi_container
    restart: always
    pull_policy: always  # Ensures the latest image is always pulled
    ports:
      - "8000:8000"
